### ISSUE TITLE
random CTD `setVisible`

### ISSUE THREAD

**Issue by AndrejAndb** [IHateMyKite/iWantWidgetsNG#1]
https://gist.github.com/AndrejAndb/e732112b75e787f2b6e834923334b81f#file-gistfile1-txt

```
Skyrim SSE v1.6.640
CrashLoggerSSE v1-8-0-0 Feb  1 2023 00:20:05

Unhandled exception "EXCEPTION_ACCESS_VIOLATION" at 0x7FF613FBDD51 SkyrimSE.exe+0F4DD51	add dword ptr [rcx+0x10], 0xFFFFFFFF

SYSTEM SPECS:
	OS: Майкрософт Windows 11 Pro v10.0.22621
	CPU: GenuineIntel 13th Gen Intel(R) Core(TM) i9-13900KF
	GPU #1: Nvidia AD103 [GeForce RTX 4080]
	GPU #2: Microsoft Basic Render Driver
	PHYSICAL MEMORY: 28.92 GB/63.78 GB

PROBABLE CALL STACK:
	[ 0] 0x7FF613FBDD51           SkyrimSE.exe+0F4DD51 -> 83181+0x41	add dword ptr [rcx+0x10], 0xFFFFFFFF
	[ 1] 0x7FF613F903F4           SkyrimSE.exe+0F203F4 -> 82278+0x184	mov rcx, [0x00007FF61613C980]
	[ 2] 0x7FF613FB82FF           SkyrimSE.exe+0F482FF -> 83102+0x15F	mov rcx, [rsp+0x80]
	[ 3] 0x7FF613FC7AB5           SkyrimSE.exe+0F57AB5 -> 83275+0xA5	movzx edx, byte ptr [rsp+0x60]
	[ 4] 0x7FF613FC7CC6           SkyrimSE.exe+0F57CC6 -> 83276+0x126	mov rcx, [rbp-0x31]
	[ 5] 0x7FF61400421F           SkyrimSE.exe+0F9421F -> 84239+0x6F	movzx edi, al
	[ 6] 0x7FF613FA2395           SkyrimSE.exe+0F32395 -> 82665+0x105	lea rbx, [r13+0x10]
	[ 7] 0x7FFA633AF24F IWantWidgetsNative.dll+002F24F
	[ 8] 0x7FFA633936EF IWantWidgetsNative.dll+00136EF
	[ 9] 0x7FFA6338CFEB IWantWidgetsNative.dll+000CFEB
	[10] 0x7FF6143E8015           SkyrimSE.exe+1378015 -> 104651+0x205	test al, al
	[11] 0x7FF6143F8D09           SkyrimSE.exe+1388D09 -> 104853+0x789	mov r14d, eax
	[12] 0x7FF61440D094           SkyrimSE.exe+139D094 -> 105176+0x834	mov ebx, eax
	[13] 0x7FF613CDC628           SkyrimSE.exe+0C6C628 -> 69378+0xD8	mov ecx, [rbx+0x0C]
	[14] 0x7FF613CDCBF1           SkyrimSE.exe+0C6CBF1 -> 69380+0x361	mov r15d, eax
	[15] 0x7FF613CDAF7A           SkyrimSE.exe+0C6AF7A -> 69344+0x8A	movzx eax, byte ptr [rbx+0xA74]
	[16] 0x7FF613CB5E4D           SkyrimSE.exe+0C45E4D -> 68445+0x3D	mov rcx, [0x00007FF616076898]
	[17] 0x7FFB1346257D           KERNEL32.DLL+001257D
	[18] 0x7FFB140EAA68              ntdll.dll+005AA68

REGISTERS:
	RAX 0x1CB0182B310      (void*)
	RCX 0x447A000045E4C000 (size_t) [4934256342910418944]
	RDX 0x593              (size_t) [1427]
	RBX 0x1CB0182B310      (void*)
	RSP 0x7D461F8C70       (void*)
	RBP 0x0                (size_t) [0]
	RSI 0x7                (size_t) [7]
	RDI 0x0                (size_t) [0]
	R8  0x2B2              (size_t) [690]
	R9  0x1CB0197D000      (void*)
	R10 0x1CB0182BAB0      (void*)
	R11 0x18               (size_t) [24]
	R12 0x0                (size_t) [0]
	R13 0x1CAE04AF168      (void*)
	R14 0x1CB02340F90      (void*)
	R15 0x7D461F8F50       (void*)

STACK:
	[RSP+0   ] 0x7D461F8D10       (void*)
	[RSP+8   ] 0x7FF613FB7D2D     (void* -> SkyrimSE.exe+0F47D2D	mov rax, [rdi+0x100])
	[RSP+10  ] 0x1CB02340F90      (void*)
	[RSP+18  ] 0x0                (size_t) [0]
	[RSP+20  ] 0x7D461F8FF0       (void*)
	[RSP+28  ] 0x7FF613F903F4     (void* -> SkyrimSE.exe+0F203F4	mov rcx, [0x00007FF61613C980])
	[RSP+30  ] 0x1CB02340F70      (void*)
	[RSP+38  ] 0x1CC12540BB0      (char*) "_root.WidgetContainer.21.widget.setVisible"
	[RSP+40  ] 0x0                (size_t) [0]
	[RSP+48  ] 0x7D461F8DB8       (void*)
	[RSP+50  ] 0x7D461F8DB8       (void*)
	[RSP+58  ] 0x7FF613FB82FF     (void* -> SkyrimSE.exe+0F482FF	mov rcx, [rsp+0x80])
	[RSP+60  ] 0x1CC2F360890      (void*)
	[RSP+68  ] 0x0                (size_t) [0]
	[RSP+70  ] 0x1CC12540BB0      (char*) "_root.WidgetContainer.21.widget.setVisible"
	[RSP+78  ] 0x1CA8AA08B20      (void*)
	[RSP+80  ] 0x7D461F8F50       (void*)
	[RSP+88  ] 0x1CC2F360910      (void*)
	[RSP+90  ] 0x1C900000002      (void*)
	[RSP+98  ] 0x7D461F9680       (void*)
	[RSP+A0  ] 0x1CC2F360890      (void*)
	[RSP+A8  ] 0x1CC2F213168      (void*)
	[RSP+B0  ] 0x7D461F8DB8       (void*)
	[RSP+B8  ] 0x0                (size_t) [0]
	[RSP+C0  ] 0x1CC12540BB0      (char*) "_root.WidgetContainer.21.widget.setVisible"
```

**Comment by IHateMyKite** [comment]
Hi, can't see anything wrong from this. Its possibly caused by race condition. Can you please try to get the CTD with following version so I get more info ? Only difference is that it have enabled logging. Note that it will dump big amount of data, so the performance might get worse.
[IWant Widgets NG 1.2.3 - Loggin.zip](https://github.com/IHateMyKite/iWantWidgetsNG/files/12712934/IWant.Widgets.NG.1.2.3.-.Loggin.zip)

**Comment by IHateMyKite** [comment]
Sorry, the files I uploaded didn't contain the updated binary with enabled logging. Please try this instead. you can then find the log in same folder as other SKSE mods.
[IWant Widgets NG 1.2.3 - Loggin.zip](https://github.com/IHateMyKite/iWantWidgetsNG/files/12729449/IWant.Widgets.NG.1.2.3.-.Loggin.zip)

**Comment by AndrejAndb** [comment]
thank you.
Not sure how fast I can reproduce it... too random (it happens that everything is fine for a few days, but sometimes 1-5 CTD in a hour)

"race condition' - actually very likely - problems usually (but not always) in the midst of a battle or other intense activity

**Comment by AndrejAndb** [comment]
I don't know why, but after I started using the debug version, I can't repeat the crashes. to make sure - I'll try the regular version (I don't know how the logging is working - maybe it adds a mutex for write to logfile)

**Comment by AndrejAndb** [comment]
[crash-2023-11-04-11-43-17.log](https://github.com/IHateMyKite/iWantWidgetsNG/files/13256601/crash-2023-11-04-11-43-17.log)
[IWantWidgetsNative.log](https://github.com/IHateMyKite/iWantWidgetsNG/files/13256602/IWantWidgetsNative.log)
[Papyrus.0.log](https://github.com/IHateMyKite/iWantWidgetsNG/files/13256604/Papyrus.0.log)

the crash log is a little different, I'm not sure if it is related

**Comment by IHateMyKite** [comment]
Looks like some kind of race condition. Can you try this version ? 
[IWant Widgets NG 1.2.4 Exp.zip](https://github.com/IHateMyKite/iWantWidgetsNG/files/13265073/IWant.Widgets.NG.1.2.4.Exp.zip) This one should apply spinlock from UI class. If it will not work, then I will release additional version which serialize certain function so no race condition can happen. Issue with that would be that there will be lag between function call and its application.

**Comment by AndrejAndb** [comment]
[crash-2023-11-22-20-34-24.log](https://github.com/IHateMyKite/iWantWidgetsNG/files/13444148/crash-2023-11-22-20-34-24.log)
(+- identical as previous crash log)


----
reproduced twice. I was install additional mods with few widgets - think it is related


---
(it seems I managed to compile, I'll try to study and analyze)

**Comment by AndrejAndb** [comment]
I now had a problem that CTD repeated constantly, but after activate `LOGGING` - crashes miraculously stopped. (re-disabling logging - crashes appeared again)

I want to rework logging a bit and test some things
